### ISSUE TITLE
vmlinux.o(.data+0xc064)

### ISSUE THREAD

**Issue by pentester** [DirtyUnicorns/android_kernel_htc_msm8974#2]
Hi,
I am trying to build kernel, but i got an error as below. Any help? Thanks you!

  LD      vmlinux.o
  MODPOST vmlinux.o
WARNING: vmlinux.o(.data+0xc064): Section mismatch in reference from the variable msm_mpm_debug_mask to the function .init.text:mpm_irq_domain_linear_size()
The variable msm_mpm_debug_mask references
the function __init mpm_irq_domain_linear_size()
If the reference is valid then annotate the
variable with __init\* or __refdata (see linux/init.h) or name the variable:
*_template, *_timer, *_sht, *_ops, *_probe, *_probe_one, *_console

WARNING: vmlinux.o(.data+0xc07c): Section mismatch in reference from the variable msm_mpm_debug_mask to the function .init.text:mpm_irq_domain_legacy_size()
The variable msm_mpm_debug_mask references
the function __init mpm_irq_domain_legacy_size()
If the reference is valid then annotate the
variable with __init\* or __refdata (see linux/init.h) or name the variable:
*_template, *_timer, *_sht, *_ops, *_probe, *_probe_one, *_console

To build the kernel despite the mismatches, build with:
'make CONFIG_NO_ERROR_ON_MISMATCH=y'
(NOTE: This is not recommended)
/home/ddos/Documents/aosp/scripts/Makefile.modpost:98: recipe for target 'vmlinux.o' failed
make[1]: **\* [vmlinux.o] Error 1
Makefile:938: recipe for target 'vmlinux.o' failed
make: **\* [vmlinux.o] Error 2

**Comment by z3ntu** [comment]
May I ask how you fixed this?
